schema: "./schema.graphql"
documents: "**/*.graphql"
extensions:
  endpoints:
    hasura:
      url: "http://localhost:8080/v1/graphql"
      headers:
        x-hasura-admin-secret: "Pwh8682W9tfx"
    middleware:
      url: "http://localhost:3000/graphql"
