version: '3.6'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: weightlifting_db
      POSTGRES_USER: weightlifting_user
      POSTGRES_PASSWORD: J8f!2gH#1kP6wQr9
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  hasura_db:
    image: postgres:latest
    environment:
      POSTGRES_DB: weightlifting_hasura_db
      POSTGRES_USER: hasura_user
      POSTGRES_PASSWORD: b43X2y3ynSNq
    ports:
      - "5433:5432"
    volumes:
      - hasura_pgdata:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:latest
    ports:
      - "8080:8080"
    depends_on:
      - "hasura_db"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura_user:b43X2y3ynSNq@hasura_db:5432/weightlifting_hasura_db
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: Pwh8682W9tfx
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "weightlifting-plan-and-track", "issuer": "https://securetoken.google.com/weightlifting-plan-and-track"}'

volumes:
  pgdata:
  hasura_pgdata:
