version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: weightlifting_db
      POSTGRES_USER: weightlifting_user
      POSTGRES_PASSWORD: J8f!2gH#1kP6wQr9

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
